config/routes.rb
MusicApp::Application.routes.draw do

  resources :bands
  resources :albums
  resources :tracks
  resources :notes, :only => [:create, :destroy]
  resources :users, :only => [:create, :new, :destroy] do
    collection do
      get 'activate'
    end
  end
  resource :session, :only => [:create, :new, :destroy]

end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :text, :track, :track_id, :author, :author_id

  validates :track_id, :presence => true
  validates :text, :presence => true,
  								 :length => { :maximum => 140 }

  validates :author_id, :presence => true

  belongs_to :track
  belongs_to :author, :class_name => User
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

	def create
		@note = Note.new(params[:note])
		if @note.save
			@track = @note.track
			redirect_to track_url(@track)
		else
			flash[:errors] ||= []
			flash[:errors] << "Bad note!"
			render :back
		end
	end

	def destroy
		@note = Note.find(params[:id])
		@track = @note.track
		@note.destroy
		redirect_to track_url(@track)
	end

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_note.html.erb
<ul>
	<% notes.each do |note| %>
		<li><%= note.text %></li>
		<% if current_user.admin? || note.author_id == current_user.id %>
			<%= button_to "Delete note", note_url(note), :method => "delete" %>
		<% end %>
	<% end %>
</ul>

<p>New note</p>

<form action="<%= notes_url %>" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<input type="hidden" name="note[track_id]" value="<%= track.id %>">
	<input type="hidden" name="note[author_id]" value="<%= current_user.id %>">

	<textarea name="note[text]" id="text"></textarea>

	<br />
	<input type="submit" value="Submit">
</form>