config/routes.rb
MusicApp::Application.routes.draw do

  resources :bands
  resources :albums
  resources :tracks
  resources :notes, :only => [:create, :destroy]
  resources :users, :only => [:create, :new, :destroy] do
    collection do
      get 'activate'
    end
  end
  resource :session, :only => [:create, :new, :destroy]

end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :ord, :title, :album, :bonus, :lyrics, :album_id

  before_create :set_bonus_default

  validates :ord, :presence => true
  								# :uniqueness => { :scope => :album_id }
  								# :within => 1..self.album.tracks.count

 	validates :title, :presence => true
 										# :uniqueness => { :scope => :album_id }

 	validates :album_id, :presence => true
 	
  belongs_to :album
  has_many :notes

  def set_bonus_default
    self.bonus ||= false
    true
  end
end

# def save_track
# 	reload!
# 	album = Album.first
# 	track = Track.new( :title => "cats", :ord => 1, :album => album )
# 	track.save!
# end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

	before_filter :current_user

	def index
		@tracks = Track.all
	end

	def show
		@track = Track.find(params[:id])
		@album = @track.album
		@band = @album.band
		@notes = @track.notes
	end

	def create
		@track = Track.create(params[:track])
		if @track.save
			redirect_to track_url(@track)
		else
			flash[:errors] ||= []
			flash[:errors] << "Invalid track name."
			redirect_to new_track_url
		end
	end

	def new
		@albums = Album.all
	end

	def update
		@track = Track.find(params[:id])
		if @track.update_attributes(params[:track])
			redirect_to track_url(@track)
		else
			flash[:errors] ||= []
			flash[:errors] << "Track update unsuccessful."
			redirect_to edit_track_url
		end
	end

	def edit
		@albums = Album.all
		@track = Track.find(params[:id])
	end

	def destroy
		@track = Track.find(params[:id])
		@album = @track.album
		@track.destroy
		redirect_to album_url(@album)
	end

end

app/helpers/tracks_helper.rb
module TracksHelper

	def ugly_lyrics(lyrics)
		music = CGI.unescapeHTML('&#9835;')
		lines = lyrics.split("\r\n")
		new_lines = lines.map { |line| "#{music} #{h(line)}" }
		lyrs = new_lines.join('<br />')
		lyrs.html_safe
	end

end

app/views/tracks/_track_form.html.erb
<% action_url = (method == :edit) ? track_url(track) : tracks_url %>

<form action="<%= action_url %>", method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<% if method == :edit %>
		<input type="hidden" value="put" name="_method">
	<% end %>

	<label>Album</label>
	<select name="track[album_id]">
		<% albums.each do |album| %>
			<option value="<%= album.id %>" <%'selected' if !track.nil? && track.album == album %>><%= album.name %></option>
		<% end %>
	</select>

	<br />

	<label for="title">Track Title</label>
	<input type="text" id="title" name="track[title]" value="<%= track.title unless track.nil? %>">

	<br />

	<label for="ord">Track Number</label>
	<input type="text" id="ord" name="track[ord]" value="<%= track.ord unless track.nil? %>">

	<br />

	<label>Bonus Track?</label>
	<select name="track[bonus]">
		<option value="no">No</option>
		<option value="yes">Yes</option>
	</select>

	<br />

	<label for="lyrics">Lyrics</label>
	<textarea name="track[lyrics]" id="lyrics" value="<%= track.lyrics unless track.nil? %>">
	</textarea>

	<br />

	<input type="submit" value="Submit">

</form>

app/views/tracks/edit.html.erb
<% flash[:errors].try(:each) do |error| %>
	<%= error %>
<% end %>

<h3>Edit Track</h3>

<%= render :partial => "track_form", :locals => { :albums => @albums,
																									:track => @track,
																								  :method => :edit } %>

app/views/tracks/new.html.erb
<% flash[:errors].try(:each) do |error| %>
	<%= error %>
<% end %>

<h3>Create New Track</h3>

<%= render :partial => "track_form", :locals => { :albums => @albums,
																									:track => @track,
																								  :method => :post } %>

app/views/tracks/show.html.erb
<h3><%= @track.title %></h3>

<h4>Track no. <%= @track.ord %> from
	<%= link_to @album.name, album_url(@album) %> by
	<%= link_to @band.name, band_url(@band) %>
</h4>

<p>Bonus track: <%= @track.bonus ? "yes" : "no" %>

<div>
	<% if @current_user.admin? %>
		<%= button_to "Delete Track", track_url(@track), :method => "delete" %>
	<% end %>
</div>

<div>
	<p> Lyrics: </p>
	<%= ugly_lyrics(@track.lyrics) %>
</div>

<div>
	<h4>Notes</h4>
	<%= render :partial => "notes/note", :locals => { :notes => @notes,
																										:track => @track,
																										:current_user => @current_user } %>
</div>