config/routes.rb
MusicApp::Application.routes.draw do

  resources :bands
  resources :albums
  resources :tracks
  resources :notes, :only => [:create, :destroy]
  resources :users, :only => [:create, :new, :destroy] do
    collection do
      get 'activate'
    end
  end
  resource :session, :only => [:create, :new, :destroy]

end

app/models/album.rb
class Album < ActiveRecord::Base
	attr_accessible :name, :year, :band, :recording_type, :band_id

	before_validation :set_recording_type_default

  validates :name, :presence => true,
  								 :uniqueness => { :scope => :band_id }

  validates :band_id, :presence => true

  validates :recording_type, :inclusion => { :in => %w(studio live) }

  belongs_to :band
  has_many :tracks, :dependent => :destroy

  def set_recording_type_default
  	self.recording_type ||= "studio"
  	true
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

	before_filter :current_user

	def index
		@albums = Album.all
	end

	def show
		@bands = Band.all
		@album = Album.find(params[:id])
		@tracks = @album.tracks# .sort_by { |track| track.ord }
		@band = Band.find(@album.band_id)
	end

	def create
		@bands = Band.all
		@album = Album.create(params[:album])
		if @album.save
			redirect_to album_url(@album)
		else
			flash[:errors] ||= []
			flash[:errors] << "Invalid album name."
			redirect_to new_album_url
		end
	end

	def new
		@bands = Band.all
	end

	def update
		@album = Album.find(params[:id])
		if @album.update_attributes(params[:album])
			redirect_to album_url(@album)
		else
			flash[:errors] ||= []
			flash[:errors] << "Album update unsuccessful."
			redirect_to edit_album_url(@album)
		end
	end

	def edit
		@bands = Band.all
		@album = Album.find(params[:id])
	end

	def destroy
		@album = Album.find(params[:id])
		@band = @album.band
		@album.destroy
		redirect_to band_url(@band)
	end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_album_form.html.erb
<% action_url = (method == :edit) ? album_url(album) : albums_url %>

<form action="<%= action_url %>", method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<% if method == :edit %>
		<input type="hidden" value="put" name="_method">
	<% end %>

	<label>Band</label>
	<select name="album[band_id]">
		<% bands.each do |band| %>
			<option value="<%= band.id %>" <%'selected' if !album.nil? && album.band == band %>><%= band.name %></option>
		<% end %>
	</select>

	<br />

	<label for="name">Album Name</label>
	<input type="text" id="name" name="album[name]" value="<%= album.name unless album.nil? %>">

	<br />

	<label for="year">Year</label>
	<input type="text" id="year" name="album[year]" value="<%= album.year unless album.nil? %>">

	<br />

	<label>Recording Type</label>
	<select name="album[recording_type]">
		<option value="studio">Studio</option>
		<option value="live">Live</option>
	</select>

	<br />

	<input type="submit" value="Submit">

</form>

app/views/albums/edit.html.erb
<% flash[:errors].try(:each) do |error| %>
	<%= error %>
<% end %>

<h3>Edit Album</h3>

<%= render :partial => "album_form", :locals => { :bands => @bands,
																									:album => @album,
																								  :method => :edit } %>

app/views/albums/new.html.erb
<% flash[:errors].try(:each) do |error| %>
	<%= error %>
<% end %>

<h3>Create New Album</h3>

<%= render :partial => "album_form", :locals => { :bands => @bands,
																									:album => @album,
																								  :method => :post } %>

app/views/albums/show.html.erb
<h3><%= @album.name %></h3>

<h4>By <%= @band.name %></h4>

<ol>
	<% @tracks.each do |track| %>
		<li><%= link_to track.title, track_url(track) %></li>
		<% if @current_user.admin? %>
			<%= button_to "Delete Track", track_url(track), :method => "delete" %>
		<% end %>
	<% end %>
</ol>

<% if @current_user.admin? %>
	<%= button_to "Delete Album", album_url(@album), :method => "delete" %>
<% end %>