config/routes.rb
MusicApp::Application.routes.draw do

  resources :bands
  resources :albums
  resources :tracks
  resources :notes, :only => [:create, :destroy]
  resources :users, :only => [:create, :new, :destroy] do
    collection do
      get 'activate'
    end
  end
  resource :session, :only => [:create, :new, :destroy]

end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :name

  validates :name, :presence => true,
  								 :uniqueness => true

  has_many :albums, :dependent => :destroy
  has_many :tracks, :through => :albums
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

	before_filter :current_user

	def index
		@bands = Band.all
	end

	def show
		@band = Band.find(params[:id])
		@albums = @band.albums
	end

	def create
		@band = Band.create([params[:band]])
		if @band.save
			redirect_to band_url(@band)
		else
			flash[:errors] ||= []
			flash[:errors] << "Invalid band name."
			redirect_to new_band_url
		end
	end

	def new
	end

	def update
		@band = Band.find(params[:id])
		if @band.update_attributes(params[:band])
			redirect_to band_url(@band)
		else
			flash[:errors] ||= []
			flash[:errors] << "Band update unsuccessful."
			redirect_to edit_band_url(@band)
		end
	end

	def edit
		@band = Band.find(params[:id])
		render :edit
	end

	def destroy
		@bands = Band.all
		Band.find(params[:id]).destroy
		redirect_to bands_url
	end

end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_band_form.html.erb
<% action_url = (method == :edit) ? band_url(band) : bands_url %>

<form action="<%= action_url %>", method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<% if method == :edit %>
		<input type="hidden" value="put" name="_method">
	<% end %>

	<label for="name">Band Name</label>
	<input type="text" id="name" name="band[name]" value="<%= band.name unless band.nil? %>">

	<input type="submit" value="Submit">

</form>

app/views/bands/edit.html.erb
<% flash[:errors].try(:each) do |error| %>
	<%= error %>
<% end %>

<h3>Edit Band</h3>

<%= render :partial => "band_form", :locals => { :band => @band,
																								 :method => :edit } %>

app/views/bands/index.html.erb
<h3>Bands</h3>

<ul>
	<% @bands.each do |band| %>
		<li><%= link_to band.name, band_url(band) %></li>
		<% if @current_user.admin? %>
			<%= button_to "Delete Band", band_url(band), :method => "delete" %>
		<% end %>
	<% end %>
</ul>

app/views/bands/new.html.erb
<% flash[:errors].try(:each) do |error| %>
	<%= error %>
<% end %>

<h3>Create New Band</h3>

<%= render :partial => "band_form", :locals => { :band => @band,
																								 :method => :post } %>

app/views/bands/show.html.erb
<h3><%= @band.name %></h3>
<% if @current_user.admin? %>
	<%= button_to "Delete Band", band_url(@band), :method => "delete" %>
<% end %>

<% @albums.each do |album| %>
	<h4>
		<%= link_to album.name, album_url(album) %>
		<% if @current_user.admin? %>
			<%= button_to "Delete Album", album_url(album), :method => "delete" %>
		<% end %>
	</h4>

	<% album.tracks.each do |track| %>
		<li><%= link_to track.title, track_url(track) %></li>
	<% end %>
<% end %>